name: CI

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]

jobs:
  build-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install deps (with cache)
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Lint  
        run: pnpm run lint
      
      - name: Format
        run: pnpm run format

      - name: Typecheck
        run: pnpm run type-check


